name: CI-DEPLOY
on:
  push:
    branches: 
      - master

jobs:
  deploy-api:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: "api/"
    steps:
      - uses: actions/checkout@v2
      - name: DockerHub
        run: |
          docker login -u ${{ secrets.DOCKER_USER }} -p ${{ secrets.DOCKER_PASSWORD }}
      
      - name: Docker image
        run: docker build . --tag gdeusdara/gces-trabalho-individual-2020-2-api:api_latest

      - name: Docker Push
        run: docker push gdeusdara/gces-trabalho-individual-2020-2-api:api_latest
